module.exports = {
  // login
  LOGIN: "LOGIN",
  LOGIN_RESPONSE: "LOGIN_RESPONSE",

  //dashboard
  LAST_ORDERS: "LAST_ORDERS",
  LAST_ORDERS_RESPONSE: "LAST_ORDERS_RESPONSE",

  REVENUE_CHART_DATA: "REVENUE_CHART_DATA",
  REVENUE_CHART_DATA_RESPONSE: "REVENUE_CHART_DATA_RESPONSE",

  EXPORT_LAST_ORDERS: "EXPORT_LAST_ORDERS",
  EXPORT_LAST_ORDERS_RESPONSE: "EXPORT_LAST_ORDERS_RESPONSE",

  // forgot password
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  FORGOT_PASSWORD_RESPONSE: "FORGOT_PASSWORD_RESPONSE",

  // get users field
  GET_USER_FIELDS: "GET_USER_FIELDS",
  GET_USER_FIELDS_RESPONSE: "GET_USER_FIELDS_RESPONSE",

  // get users field value
  GET_USER_FIELDS_UPDATE_VALUE: "GET_USER_FIELDS_UPDATE_VALUE",
  GET_USER_FIELDS_UPDATE_VALUE_RESPONSE:
    "GET_USER_FIELDS_UPDATE_VALUE_RESPONSE",

  // get users
  GET_USER: "GET_USER",
  GET_USER_RESPONSE: "GET_USER_RESPONSE",

  // add users
  ADD_USER: "ADD_USER",
  ADD_USER_RESPONSE: "ADD_USER_RESPONSE",

  // edit user
  EDIT_USER: "EDIT_USER",
  EDIT_USER_RESPONSE: "EDIT_USER_RESPONSE",

  // delete user
  DELETE_USER: "DELETE_USER",
  DELETE_USER_RESPONSE: "DELETE_USER_RESPONSE",

  //download users
  DOWNLOAD_USERS: "DOWNLOAD_USERS",
  DOWNLOAD_USERS_RESPONSE: "DOWNLOAD_USERS_RESPONSE",

  // stores for store supervisor
  GET_STORES: "GET_STORES",
  GET_STORES_RESPONSE: "GET_STORES_RESPONSE",

  //to get Approval request from admin
  GET_STORE_UPDATE_REQUESTS: "GET_STORE_UPDATE_REQUESTS",
  GET_STORE_UPDATE_REQUESTS_RESPONSE: "GET_STORE_UPDATE_REQUESTS_RESPONSE",

  //sending approve response back to store  supervisor
  STORE_UPDATE_APPROVED: "STORE_UPDATE_APPROVED",
  STORE_UPDATE_APPROVED_RESPONSE: "STORE_UPDATE_APPROVED_RESPONSE",

  //sending  reject response back to store  supervisor
  STORE_UPDATE_REJECTED: "STORE_UPDATE_REJECTED",
  STORE_UPDATE_REJECTED_RESPONSE: "STORE_UPDATE_REJECTED_RESPONSE",

  // get roles
  GET_ROLES: "GET_ROLES",
  GET_ROLES_RESPONSE: "GET_ROLES_RESPONSE",

  // get common users
  GET_COMMON_USERS: "GET_COMMON_USERS",
  GET_COMMON_USERS_RESPONSE: "GET_COMMON_USERS_RESPONSE",

  //get emergency contacts
  GET_EMERGENCY_CONTACTS: "GET_EMERGENCY_CONTACTS",
  GET_EMERGENCY_CONTACTS_RESPONSE: "GET_EMERGENCY_CONTACTS_RESPONSE",

  ADD_EMERGENCY_CONTACTS: "ADD_EMERGENCY_CONTACTS",
  ADD_EMERGENCY_CONTACTS_RESPONSE: "ADD_EMERGENCY_CONTACTS_RESPONSE",

  UPDATE_EMERGENCY_CONTACTS: "UPDATE_EMERGENCY_CONTACTS",
  UPDATE_EMERGENCY_CONTACTS_RESPONSE: "UPDATE_EMERGENCY_CONTACTS_RESPONSE",

  DELETE_EMERGENCY_CONTACTS: "DELETE_EMERGENCY_CONTACTS",
  DELETE_EMERGENCY_CONTACTS_RESPONSE: "DELETE_EMERGENCY_CONTACTS_RESPONSE",

  ADD_EMERGENCY_CONTACTS_DETAILS: "ADD_EMERGENCY_CONTACTS_DETAILS",
  ADD_EMERGENCY_CONTACTS_DETAILS_RESPONSE:
    "ADD_EMERGENCY_CONTACTS_DETAILS_RESPONSE",

  UPDATE_EMERGENCY_CONTACTS_DETAILS: "UPDATE_EMERGENCY_CONTACTS_DETAILS",
  UPDATE_EMERGENCY_CONTACTS_DETAILS_RESPONSE:
    "UPDATE_EMERGENCY_CONTACTS_DETAILS_RESPONSE",

  DELETE_EMERGENCY_CONTACTS_DETAILS: "DELETE_EMERGENCY_CONTACTS_DETAILS",
  DELETE_EMERGENCY_CONTACTS_DETAILS_RESPONSE:
    "DELETE_EMERGENCY_CONTACTS_DETAILS_RESPONSE",

  // get airport fields
  GET_AIRPORT_FIELDS: "GET_AIRPORT_FIELDS",
  GET_AIRPORT_FIELDS_RESPONSE: "GET_AIRPORT_FIELDS_RESPONSE",

  // get airport fields update value
  GET_AIRPORT_FIELDS_UPDATE_VALUE: "GET_AIRPORT_FIELDS_UPDATE_VALUE",
  GET_AIRPORT_FIELDS_UPDATE_VALUE_RESPONSE:
    "GET_AIRPORT_FIELDS_UPDATE_VALUE_RESPONSE",

  GET_ACTIVE_AIRPORTS: "GET_ACTIVE_AIRPORTS",
  GET_ACTIVE_AIRPORTS_RESPONSE: "GET_ACTIVE_AIRPORTS_RESPONSE",

  // get airports
  GET_AIRPORTS: "GET_AIRPORTS",
  GET_AIRPORTS_RESPONSE: " GET_AIRPORTS_RESPONSE",

  // get airport details
  GET_AIRPORTS_DETAILS: "GET_AIRPORTS_DETAILS",
  GET_AIRPORTS_DETAILS_RESPONSE: " GET_AIRPORTS_DETAILS_RESPONSE",

  // add airport
  ADD_AIRPORT: "ADD_AIRPORT",
  ADD_AIRPORT_RESPONSE: " ADD_AIRPORT_RESPONSE",

  // download airports
  DOWNLOAD_AIRPORTS: "DOWNLOAD_AIRPORTS",
  DOWNLOAD_AIRPORTS_RESPONSE: "DOWNLOAD_AIRPORTS_RESPONSE",

  // edit airport
  EDIT_AIRPORT: "EDIT_AIRPORT",
  EDIT_AIRPORT_RESPONSE: "EDIT_AIRPORT_RESPONSE",

  // delete airport
  DELETE_AIRPORT: "DELETE_AIRPORT",
  DELETE_AIRPORT_RESPONSE: "DELETE_AIRPORT_RESPONSE",

  //airline punctality
  AIRLINE_PUNCTUALITY_FIELDS: "AIRLINE_PUNCTUALITY_FIELDS",
  AIRLINE_PUNCTUALITY_FIELDS_RESPONSE: "AIRLINE_PUNCTUALITY_FIELDS_RESPONSE",

  AIRLINE_PUNCTUALITY_FIELDS_UPDATE_VALUE:
    "AIRLINE_PUNCTUALITY_FIELDS_UPDATE_VALUE",
  AIRLINE_PUNCTUALITY_FIELDS_UPDATE_VALUE_RESPONSE:
    "AIRLINE_PUNCTUALITY_FIELDS_UPDATE_VALUE_RESPONSE",

  AIRLINE_PUNCTUALITY: "AIRLINE_PUNCTUALITY",
  AIRLINE_PUNCTUALITY_RESPONSE: "AIRLINE_PUNCTUALITY_RESPONSE",

  ADD_AIRLINE_PUNCTUALITY: "ADD_AIRLINE_PUNCTUALITY",
  ADD_AIRLINE_PUNCTUALITY_RESPONSE: "ADD_AIRLINE_PUNCTUALITY_RESPONSE",

  EDIT_AIRLINE_PUNCTUALITY: "EDIT_AIRLINE_PUNCTUALITY",
  EDIT_AIRLINE_PUNCTUALITY_RESPONSE: "EDIT_AIRLINE_PUNCTUALITY_RESPONSE",

  DELETE_AIRLINE_PUNCTUALITY: "DELETE_AIRLINE_PUNCTUALITY",
  DELETE_AIRLINE_PUNCTUALITY_RESPONSE: "DELETE_AIRLINE_PUNCTUALITY_RESPONSE",

  //airbus
  AIRBUS_INFO_FIELDS: "AIRBUS_INFO_FIELDS",
  AIRBUS_INFO_FIELDS_RESPONSE: "AIRBUS_INFO_FIELDS_RESPONSE",

  AIRBUS_INFO_FIELDS_UPDATE_VALUE: "AIRBUS_INFO_FIELDS_UPDATE_VALUE",
  AIRBUS_INFO_FIELDS_UPDATE_VALUE_RESPONSE:
    "AIRBUS_INFO_FIELDS_UPDATE_VALUE_RESPONSE",
  AIRBUS_INFO: "AIRBUS_INFO",
  AIRBUS_INFO_RESPONSE: "AIRBUS_INFO_RESPONSE",

  ADD_AIRBUS_INFO: "ADD_AIRBUS_INFO",
  ADD_AIRBUS_INFO_RESPONSE: "ADD_AIRBUS_INFO_RESPONSE",

  EDIT_AIRBUS_INFO: "EDIT_AIRBUS_INFO",
  EDIT_AIRBUS_INFO_RESPONSE: "EDIT_AIRBUS_INFO_RESPONSE",

  DELETE_AIRBUS_INFO: "DELETE_AIRBUS_INFO",
  DELETE_AIRBUS_INFO_RESPONSE: "DELETE_AIRBUS_INFO_RESPONSE",

  AIRLINE_DETAILS_FIELDS: "AIRLINE_DETAILS_FIELDS",
  AIRLINE_DETAILS_FIELDS_RESPONSE: "AIRLINE_DETAILS_FIELDS_RESPONSE",

  AIRLINE_DETAILS_FIELDS_UPDATE_VALUE: "AIRLINE_DETAILS_FIELDS_UPDATE_VALUE",
  AIRLINE_DETAILS_FIELDS_UPDATE_VALUE_RESPONSE:
    "AIRLINE_DETAILS_FIELDS_UPDATE_VALUE_RESPONSE",

  AIRLINE_DETAILS: "AIRLINE_DETAILS",
  AIRLINE_DETAILS_RESPONSE: "AIRLINE_DETAILS_RESPONSE",

  ADD_AIRLINE_DETAILS: "ADD_AIRLINE_DETAILS",
  ADD_AIRLINE_DETAILS_RESPONSE: "ADD_AIRLINE_DETAILS_RESPONSE",

  EDIT_AIRLINE_DETAILS: "EDIT_AIRLINE_DETAILS",
  EDIT_AIRLINE_DETAILS_RESPONSE: "EDIT_AIRLINE_DETAILS_RESPONSE",

  DELETE_AIRLINE_DETAILS: "DELETE_AIRLINE_DETAILS",
  DELETE_AIRLINE_DETAILS_RESPONSE: "DELETE_AIRLINE_DETAILS_RESPONSE",
  // terminal
  GET_TERMINAL_FIELDS: "GET_TERMINAL_FIELDS",
  GET_TERMINAL_FIELDS_RESPONSE: "GET_TERMINAL_FIELDS_RESPONSE",

  // terminal update field value
  GET_TERMINAL_FIELDS_UPDATE_VALUE: "GET_TERMINAL_FIELDS_UPDATE_VALUE",
  GET_TERMINAL_FIELDS_UPDATE_VALUE_RESPONSE:
    "GET_TERMINAL_FIELDS_UPDATE_VALUE_RESPONSE",

  // get terminals
  GET_TERMINALS: "GET_TERMINALS",
  GET_TERMINALS_RESPONSE: "GET_TERMINALS_RESPONSE",

  // add terminal
  ADD_TERMINAL: "ADD_TERMINAL",
  ADD_TERMINAL_RESPONSE: "ADD_TERMINAL_RESPONSE",

  // edit terminal
  EDIT_TERMINAL: "EDIT_TERMINAL",
  EDIT_TERMINAL_RESPONSE: "EDIT_TERMINAL_RESPONSE",

  // delete terminal
  DELETE_TERMINAL: "DELETE_TERMINAL",
  DELETE_TERMINAL_RESPONSE: "DELETE_TERMINAL_RESPONSE",

  // get store fields
  GET_STORE_FIELDS: "GET_STORE_FIELDS",
  GET_STORE_FIELDS_RESPONSE: "GET_STORE_FIELDS_RESPONSE",

  // get store update value
  GET_STORE_FIELDS_UPDATE_VALUE: "GET_STORE_FIELDS_UPDATE_VALUE",
  GET_STORE_FIELDS_UPDATE_VALUE_RESPONSE:
    "GET_STORE_FIELDS_UPDATE_VALUE_RESPONSE",

  // get outlets
  GET_OUTLETS: "GET_OUTLETS",
  GET_OUTLETS_RESPONSE: "GET_OUTLETS_RESPONSE",

  // get sub category
  GET_SUB_CATEGORY: "GET_SUB_CATEGORY",
  GET_SUB_CATEGORY_RESPONSE: "GET_SUB_CATEGORY_RESPONSE",

  // category

  // add category
  ADD_CATEGORY: "ADD_CATEGORY",
  ADD_CATEGORY_RESPONSE: "ADD_CATEGORY_RESPONSE",

  // edit category
  EDIT_CATEGORY: "EDIT_CATEGORY",
  EDIT_CATEGORY_RESPONSE: "EDIT_CATEGORY_RESPONSE",

  // delete category
  DELETE_CATEGORY: " DELETE_CATEGORY",
  DELETE_CATEGORY_RESPONSE: " DELETE_CATEGORY_RESPONSE",

  // sub-category

  // add category
  ADD_SUB_CATEGORY: "ADD_SUB_CATEGORY",
  ADD_SUB_CATEGORY_RESPONSE: "ADD_SUB_CATEGORY_RESPONSE",

  // edit category
  EDIT_SUB_CATEGORY: "EDIT_SUB_CATEGORY",
  EDIT_SUB_CATEGORY_RESPONSE: "EDIT_SUB_CATEGORY_RESPONSE",

  // delete category
  DELETE_SUB_CATEGORY: "DELETE_SUB_CATEGORY",
  DELETE_SUB_CATEGORY_RESPONSE: "DELETE_SUB_CATEGORY_RESPONSE",

  // add outlets
  ADD_OUTLETS: "ADD_OUTLETS",
  ADD_OUTLETS_RESPONSE: "ADD_OUTLETS_RESPONSE",

  // edit outlets
  EDIT_OUTLETS: "EDIT_OUTLETS",
  EDIT_OUTLETS_RESPONSE: "EDIT_OUTLETS_RESPONSE",

  // delete otutlets
  DELETE_OUTLETS: "DELETE_OUTLETS",
  DELETE_OUTLETS_RESPONSE: "DELETE_OUTLETS_RESPONSE",

  //preferences

  SEAMLESS_FIELDS: "SEAMLESS_FIELDS",
  SEAMLESS_FIELDS_RESPONSE: "SEAMLESS_FIELDS_RESPONSE",

  SEAMLESS_FIELDS_UPDATE_VALUE: "SEAMLESS_FIELDS_UPDATE_VALUE",
  SEAMLESS_FIELDS_UPDATE_VALUE_RESPONSE:
    "SEAMLESS_FIELDS_UPDATE_VALUE_RESPONSE",

  SEAMLESS_VALUES_FIELDS: "SEAMLESS_VALUES_FIELDS",
  SEAMLESS_VALUES_FIELDS_RESPONSE: "SEAMLESS_VALUES_FIELDS_RESPONSE",

  SEAMLESS_VALUES_FIELDS_UPDATE_VALUE: "SEAMLESS_VALUES_FIELDS_UPDATE_VALUE",
  SEAMLESS_VALUES_FIELDS_UPDATE_VALUE_RESPONSE:
    "SEAMLESS_VALUES_FIELDS_UPDATE_VALUE_RESPONSE",

  SEAMLESS: "SEAMLESS",
  SEAMLESS_RESPONSE: "SEAMLESS_RESPONSE",

  ADD_SEAMLESS: "ADD_SEAMLESS",
  ADD_SEAMLESS_RESPONSE: "ADD_SEAMLESS_RESPONSE",

  UPDATE_SEAMLESS: "UPDATE_SEAMLESS",
  UPDATE_SEAMLESS_RESPONSE: "UPDATE_SEAMLESS_RESPONSE",

  DELETE_SEAMLESS: "DELETE_SEAMLESS",
  DELETE_SEAMLESS_RESPONSE: "DELETE_SEAMLESS_RESPONSE",

  ADD_SEAMLESS_VALUES: "ADD_SEAMLESS_VALUES",
  ADD_SEAMLESS_VALUES_RESPONSE: "ADD_SEAMLESS_VALUES_RESPONSE",

  UPDATE_SEAMLESS_VALUES: "UPDATE_SEAMLESS_VALUES",
  UPDATE_SEAMLESS_VALUES_RESPONSE: "UPDATE_SEAMLESS_VALUES_RESPONSE",

  DELETE_SEAMLESS_VALUES: "DELETE_SEAMLESS_VALUES",
  DELETE_SEAMLESS_VALUES_RESPONSE: "DELETE_SEAMLESS_VALUES_RESPONSE",

  EXCITING_FIELDS: "EXCITING_FIELDS",
  EXCITING_FIELDS_RESPONSE: "EXCITING_FIELDS_RESPONSE",

  EXCITING_FIELDS_UPDATE_VALUE: "EXCITING_FIELDS_UPDATE_VALUE",
  EXCITING_FIELDS_UPDATE_VALUE_RESPONSE:
    "EXCITING_FIELDS_UPDATE_VALUE_RESPONSE",

  EXCITING_VALUES_FIELDS: "EXCITING_VALUES_FIELDS",
  EXCITING_VALUES_FIELDS_RESPONSE: "EXCITING_VALUES_FIELDS_RESPONSE",

  EXCITING_VALUES_FIELDS_UPDATE_VALUE: "EXCITING_VALUES_FIELDS_UPDATE_VALUE",
  EXCITING_VALUES_FIELDS_UPDATE_VALUE_RESPONSE:
    "EXCITING_VALUES_FIELDS_UPDATE_VALUE_RESPONSE",

  EXCITING: "EXCITING",
  EXCITING_RESPONSE: "EXCITING_RESPONSE",

  ADD_EXCITING: "ADD_EXCITING",
  ADD_EXCITING_RESPONSE: "ADD_EXCITING_RESPONSE",

  UPDATE_EXCITING: "UPDATE_EXCITING",
  UPDATE_EXCITING_RESPONSE: "UPDATE_EXCITING_RESPONSE",

  DELETE_EXCITING: "DELETE_EXCITING",
  DELETE_EXCITING_RESPONSE: "DELETE_EXCITING_RESPONSE",

  ADD_EXCITING_VALUES: "ADD_EXCITING_VALUES",
  ADD_EXCITING_VALUES_RESPONSE: "ADD_EXCITING_VALUES_RESPONSE",

  UPDATE_EXCITING_VALUES: "UPDATE_EXCITING_VALUES",
  UPDATE_EXCITING_VALUES_RESPONSE: "UPDATE_EXCITING_VALUES_RESPONSE",

  DELETE_EXCITING_VALUES: "DELETE_EXCITING_VALUES",
  DELETE_EXCITING_VALUES_RESPONSE: "DELETE_EXCITING_VALUES_RESPONSE",

  //upcoming stores
  GET_UPCOMING_STORES_FIELDS: "GET_UPCOMING_STORES_FIELDS",
  GET_UPCOMING_STORES_FIELDS_RESPONSE: "GET_UPCOMING_STORES_FIELDS_RESPONSE",

  // UPCOMING_STORES update field value
  GET_UPCOMING_STORES_FIELDS_UPDATE_VALUE:
    "GET_UPCOMING_STORES_FIELDS_UPDATE_VALUE",
  GET_UPCOMING_STORES_FIELDS_UPDATE_VALUE_RESPONSE:
    "GET_UPCOMING_STORES_FIELDS_UPDATE_VALUE_RESPONSE",

  // get UPCOMING_STORES
  GET_UPCOMING_STORES: "GET_UPCOMING_STORES",
  GET_UPCOMING_STORES_RESPONSE: "GET_UPCOMING_STORES_RESPONSE",

  // add UPCOMING_STORES
  ADD_UPCOMING_STORES: "ADD_UPCOMING_STORES",
  ADD_UPCOMING_STORES_RESPONSE: "ADD_UPCOMING_STORES_RESPONSE",

  // edit UPCOMING_STORES
  EDIT_UPCOMING_STORES: "EDIT_UPCOMING_STORES",
  EDIT_UPCOMING_STORES_RESPONSE: "EDIT_UPCOMING_STORES_RESPONSE",

  // delete UPCOMING_STORES
  DELETE_UPCOMING_STORES: "DELETE_UPCOMING_STORES",
  DELETE_UPCOMING_STORES_RESPONSE: "DELETE_UPCOMING_STORES_RESPONSE",

  // stores offer
  GET_STORES_OFFER_FIELDS: "GET_STORES_OFFER_FIELDS",
  GET_STORES_OFFER_FIELDS_RESPONSE: "GET_STORES_OFFER_FIELDS_RESPONSE",

  // STORES_OFFER update field value
  GET_STORES_OFFER_FIELDS_UPDATE_VALUE: "GET_STORES_OFFER_FIELDS_UPDATE_VALUE",
  GET_STORES_OFFER_FIELDS_UPDATE_VALUE_RESPONSE:
    "GET_STORES_OFFER_FIELDS_UPDATE_VALUE_RESPONSE",

  // get STORES_OFFER
  GET_STORES_OFFER: "GET_STORES_OFFER",
  GET_STORES_OFFER_RESPONSE: "GET_STORES_OFFER_RESPONSE",

  // add STORES_OFFER
  ADD_STORES_OFFER: "ADD_STORES_OFFER",
  ADD_STORES_OFFER_RESPONSE: "ADD_STORES_OFFER_RESPONSE",

  // edit STORES_OFFER
  EDIT_STORES_OFFER: "EDIT_STORES_OFFER",
  EDIT_STORES_OFFER_RESPONSE: "EDIT_STORES_OFFER_RESPONSE",

  // delete STORES_OFFER
  DELETE_STORES_OFFER: "DELETE_STORES_OFFER",
  DELETE_STORES_OFFER_RESPONSE: "DELETE_STORES_OFFER_RESPONSE",

  //  BAGGAGE_INFO offer
  GET_BAGGAGE_INFO_FIELDS: "GET_BAGGAGE_INFO_FIELDS",
  GET_BAGGAGE_INFO_FIELDS_RESPONSE: "GET_BAGGAGE_INFO_FIELDS_RESPONSE",

  // BAGGAGE_INFO update field value
  GET_BAGGAGE_INFO_FIELDS_UPDATE_VALUE: "GET_BAGGAGE_INFO_FIELDS_UPDATE_VALUE",
  GET_BAGGAGE_INFO_FIELDS_UPDATE_VALUE_RESPONSE:
    "GET_BAGGAGE_INFO_FIELDS_UPDATE_VALUE_RESPONSE",

  // get BAGGAGE_INFO
  GET_BAGGAGE_INFO: "GET_BAGGAGE_INFO",
  GET_BAGGAGE_INFO_RESPONSE: "GET_BAGGAGE_INFO_RESPONSE",

  // add BAGGAGE_INFO
  ADD_BAGGAGE_INFO: "ADD_BAGGAGE_INFO",
  ADD_BAGGAGE_INFO_RESPONSE: "ADD_BAGGAGE_INFO_RESPONSE",

  // edit BAGGAGE_INFO
  EDIT_BAGGAGE_INFO: "EDIT_BAGGAGE_INFO",
  EDIT_BAGGAGE_INFO_RESPONSE: "EDIT_BAGGAGE_INFO_RESPONSE",

  // delete BAGGAGE_INFO
  DELETE_BAGGAGE_INFO: "DELETE_BAGGAGE_INFO",
  DELETE_BAGGAGE_INFO_RESPONSE: "DELETE_BAGGAGE_INFO_RESPONSE",

  // ETA_TRIP offer
  ETA_TRIP_FIELDS: "ETA_TRIP_FIELDS",
  ETA_TRIP_FIELDS_RESPONSE: "ETA_TRIP_FIELDS_RESPONSE",

  // ETA_TRIP update field value
  ETA_TRIP_FIELDS_UPDATE_VALUE: "ETA_TRIP_FIELDS_UPDATE_VALUE",
  ETA_TRIP_FIELDS_UPDATE_VALUE_RESPONSE:
    "ETA_TRIP_FIELDS_UPDATE_VALUE_RESPONSE",

  // get ETA_TRIP
  ETA_TRIP: "ETA_TRIP",
  ETA_TRIP_RESPONSE: "ETA_TRIP_RESPONSE",

  // add ETA_TRIP
  ADD_ETA_TRIP: "ADD_ETA_TRIP",
  ADD_ETA_TRIP_RESPONSE: "ADD_ETA_TRIP_RESPONSE",

  // edit ETA_TRIP
  EDIT_ETA_TRIP: "EDIT_ETA_TRIP",
  EDIT_ETA_TRIP_RESPONSE: "EDIT_ETA_TRIP_RESPONSE",

  // delete ETA_TRIP
  DELETE_ETA_TRIP: "DELETE_ETA_TRIP",
  DELETE_ETA_TRIP_RESPONSE: "DELETE_ETA_TRIP_RESPONSE",

  // ETA_TRIP offer
  COUNTRY_DETAILS_FIELDS: "COUNTRY_DETAILS_FIELDS",
  COUNTRY_DETAILS_FIELDS_RESPONSE: "COUNTRY_DETAILS_FIELDS_RESPONSE",

  // COUNTRY_DETAILS update field value
  COUNTRY_DETAILS_FIELDS_UPDATE_VALUE: "COUNTRY_DETAILS_FIELDS_UPDATE_VALUE",
  COUNTRY_DETAILS_FIELDS_UPDATE_VALUE_RESPONSE:
    "COUNTRY_DETAILS_FIELDS_UPDATE_VALUE_RESPONSE",

  // get COUNTRY_DETAILS
  COUNTRY_DETAILS: "COUNTRY_DETAILS",
  COUNTRY_DETAILS_RESPONSE: "COUNTRY_DETAILS_RESPONSE",

  // add COUNTRY_DETAILS
  ADD_COUNTRY_DETAILS: "ADD_COUNTRY_DETAILS",
  ADD_COUNTRY_DETAILS_RESPONSE: "ADD_COUNTRY_DETAILS_RESPONSE",

  // edit COUNTRY_DETAILS
  EDIT_COUNTRY_DETAILS: "EDIT_COUNTRY_DETAILS",
  EDIT_COUNTRY_DETAILS_RESPONSE: "EDIT_COUNTRY_DETAILS_RESPONSE",

  // delete COUNTRY_DETAILS
  DELETE_COUNTRY_DETAILS: "DELETE_COUNTRY_DETAILS",
  DELETE_COUNTRY_DETAILS_RESPONSE: "DELETE_COUNTRY_DETAILS_RESPONSE",

  // upload file
  UPLOAD_FILE: "UPLOAD_FILE",
  UPLOAD_FILE_RESPONSE: "UPLOAD_FILE_RESPONSE",

  // bulk upload
  BULK_UPLOAD: "BULK_UPLOAD",
  BULK_UPLOAD_RESPONSE: "BULK_UPLOAD_RESPONSE",

  // non API actions
  PAGE_REFRESHING_RESPONSE: "PAGE_REFRESHING_RESPONSE",

  // upload file
  UPLOAD_BARCODE: "UPLOAD_BARCODE",
  UPLOAD_BARCODE_RESPONSE: "UPLOAD_BARCODE_RESPONSE",

  UPLOAD_REDEEM: "UPLOAD_REDEEM",
  UPLOAD_REDEEM_RESPONSE: "UPLOAD_REDEEM_RESPONSE",

  
  // get cancel message fields
  GET_CANCEL_MESSAGE_FIELDS: "GET_CANCEL_MESSAGE_FIELDS",
  GET_CANCEL_MESSAGE_FIELDS_RESPONSE: "GET_CANCEL_MESSAGE_FIELDS_RESPONSE",

  // get cancel message fields update value
  GET_CANCEL_MESSAGE_FIELDS_UPDATE_VALUE: "GET_CANCEL_MESSAGE_FIELDS_UPDATE_VALUE",
  GET_CANCEL_MESSAGE_FIELDS_UPDATE_VALUE_RESPONSE:
    "GET_CANCEL_MESSAGE_FIELDS_UPDATE_VALUE_RESPONSE",


  // get cancel message
  GET_CANCEL_MESSAGE: "GET_CANCEL_MESSAGE",
  GET_CANCEL_MESSAGE_RESPONSE: " GET_CANCEL_MESSAGE_RESPONSE",

  // get cancel message
  GET_CANCEL_MESSAGE_DETAILS: "GET_CANCEL_MESSAGE_DETAILS",
  GET_CANCEL_MESSAGE_DETAILS_RESPONSE: " GET_CANCEL_MESSAGE_DETAILS_RESPONSE",

  // add cancel message
  ADD_CANCEL_MESSAGE: "ADD_CANCEL_MESSAGE",
  ADD_CANCEL_MESSAGE_RESPONSE: " ADD_CANCEL_MESSAGE_RESPONSE",

  // download cancel message
  DOWNLOAD_CANCEL_MESSAGE: "DOWNLOAD_CANCEL_MESSAGE",
  DOWNLOAD_CANCEL_MESSAGE_RESPONSE: "DOWNLOAD_CANCEL_MESSAGE_RESPONSE",

  // edit cancel message
  EDIT_CANCEL_MESSAGE: "EDIT_CANCEL_MESSAGE",
  EDIT_CANCEL_MESSAGE_RESPONSE: "EDIT_CANCEL_MESSAGE_RESPONSE",

  // delete cancel message
  DELETE_CANCEL_MESSAGE: "DELETE_CANCEL_MESSAGE",
  DELETE_CANCEL_MESSAGE_RESPONSE: "DELETE_CANCEL_MESSAGE_RESPONSE",

};
